name = "nut-api-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
DEEPGRAM_API = "https://api.deepgram.com/v1/listen"
DEEPSEEK_API = "https://api.deepseek.com/v1/chat/completions"
